[Doc] to add htap multi node
polardb/PolarDB-for-PostgreSQL pull request #250
Opened 2022-05-31 13:36 UTC by HBKO

Add the htap multi node

2022-05-31 15:52 UTC, mrdrivingduck requested changes

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
>  ## 执行 PolarDB HTAP 跨机并行查询
在标题上可以突出一下这三种部署方式的区别：

![image](https://user-images.githubusercontent.com/32560442/171212693-5b24bc2b-75f0-4040-bb83-686339bbdcd5.png)

- 执行 PostgreSQL 单机并行执行
- 执行 PolarDB HTAP 单机并行执行
- 执行 PolarDB HTAP 跨机并行执行

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
>  在体验完单机并行查询后，我们开启跨机并行查询。然后使用相同的数据，重新体验一下查询性能。
在体验完单机并行查询后，我们开启 PolarDB HTAP 的并行执行，在单机上重新体验一下查询性能。

> tip 可以去掉了，因为标题已经说得足够明白了。

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +执行前提，在编译通过且有 `./tmp_basedir_polardb_pg_1100_bld/` 、 `./tmp_replica_dir_polardb_pg_1100_bld1/` 和 `./tmp_replica_dir_polardb_pg_1100_bld2/` 目录的情况下可以通过如下的命令，在不同机器上启动对应的 replica 结点：
这还是不是一个通顺的句子。可以这样写：

执行前提：

- 代码编译通过
- 存在 `~/tmp_basedir_polardb_pg_1100_bld/`、`~/tmp_replica_dir_polardb_pg_1100_bld1/`、`~/tmp_replica_dir_polardb_pg_1100_bld2/` 目录

通过以下命令在不同机器上启动 replica 节点：

......

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +启动完两个只读结点后，可以通过 `ps -efww` 看两个只读结点的端口：
启动两个只读结点后，可以通过 `ps -efww` 查看两个只读结点的端口：

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +一个在 5433 ，一个在 5432 端口，这个也可以通过 `polardb_build.sh` 进行调整。
进程分别运行在 `5433` 端口和 `5432` 端口，可以通过 `polardb_build.sh` 进行调整。

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +确认不同结点之间是连通的，可以通过下面的命令验证：
病句。

通过下面的命令验证主节点到只读结点的连通性。如果访问不通，请检查防火墙等网络配置。

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +对只读结点进行访问，如果访问不通，请检查防火墙等网络配置。
删了

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +-- 进入 psql
这个注释和下面的 SQL 没什么联系，可以拉到外面。

进入 `psql` 命令行后，执行以下 SQL 语句：

```sql
- 将 IP 地址更换成只读节点的 IP
alter system set polar_cluster_map=polar_cluster_map='node1|127.0.0.1|5433,node2|127.0.0.1|5434';
select pg_reload_conf();
```

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +-- 以 TPC-H 为例，可以检查计划中是否有 PX
这个注释同样可以拉到上面作为文字，没必要写在这个注释里。

以 TPC-H 为例，检查查询计划是否来自于 PolarDB 的 PX 优化器，并执行查询：

```sql
explain select count(*) from customer;
select count(*) from customer;
```

2022-05-31 15:52 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +如果发现下面的错误，可以尝试修改每台机器的 `mtu` 为 9000 统一。
原句是个病句，啥叫 `修改 xxx 为 9000 统一`。

如果发现下面的错误，可以尝试统一修改每台机器的 MTU 为 `9000`。

> 如果这是一个专有名词，就不需要使用 `` 包裹。

2022-05-31 15:55 UTC, mrdrivingduck requested changes

2022-05-31 15:55 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +```sql
这里用 shell，你下面执行的命令是 shell 而不是 SQL。

2022-06-01 09:14 UTC, HBKO commented on docs/guide/tpch-on-px.md
>  ## 执行 PolarDB HTAP 跨机并行查询
Done

2022-06-01 09:14 UTC, HBKO commented on docs/guide/tpch-on-px.md
>  在体验完单机并行查询后，我们开启跨机并行查询。然后使用相同的数据，重新体验一下查询性能。
Done

2022-06-01 09:14 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +执行前提，在编译通过且有 `./tmp_basedir_polardb_pg_1100_bld/` 、 `./tmp_replica_dir_polardb_pg_1100_bld1/` 和 `./tmp_replica_dir_polardb_pg_1100_bld2/` 目录的情况下可以通过如下的命令，在不同机器上启动对应的 replica 结点：
Done

2022-06-01 09:17 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +启动完两个只读结点后，可以通过 `ps -efww` 看两个只读结点的端口：
Done

2022-06-01 09:17 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +一个在 5433 ，一个在 5432 端口，这个也可以通过 `polardb_build.sh` 进行调整。
Done

2022-06-01 09:17 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +确认不同结点之间是连通的，可以通过下面的命令验证：
Done

2022-06-01 09:17 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +```sql
Done

2022-06-01 09:18 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +对只读结点进行访问，如果访问不通，请检查防火墙等网络配置。
Done

2022-06-01 09:18 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +-- 进入 psql
Done

2022-06-01 09:18 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +-- 以 TPC-H 为例，可以检查计划中是否有 PX
Done

2022-06-01 09:18 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +如果发现下面的错误，可以尝试修改每台机器的 `mtu` 为 9000 统一。
Done

2022-06-01 16:26 UTC, mrdrivingduck requested changes

2022-06-01 16:26 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +- 存在 `./tmp_basedir_polardb_pg_1100_bld/` 、 `./tmp_replica_dir_polardb_pg_1100_bld1/` 和 `./tmp_replica_dir_polardb_pg_1100_bld2/` 目录
这里用绝对路径吧，因为你不能假设用户现在在哪个路径下。

`~/tmp_xxx`

2022-06-01 16:26 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +./tmp_basedir_polardb_pg_1100_bld/bin/pg_ctl -D ./tmp_replica_dir_polardb_pg_1100_bld1/ restart
同上，用户可能只会复制粘贴。如果当前用户没在 home 目录下就会有错误。

2022-06-01 16:26 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +```
![image](https://user-images.githubusercontent.com/32560442/171452947-873226b8-51f5-450f-9fd8-c5d3d71021e8.png)

参考上图，这里可以在上面加一个 warning，提示用户更换 `<ip_address>` 和 `<port>` 为 IP 地址和端口号。

```shell
psql -h <ip_address> -p <port> -Upostgres postgres
```

2022-06-01 16:26 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +```
同上，这里的 `--` 注释可以不要了。加入一个 waning 提醒用户更换 `<ip_address_1>` 的内容。

```sql
alter system set polar_cluster_map=polar_cluster_map='node1|<ip_address_1>|5433,node2|<ip_address_2>|5434';
select pg_reload_conf();
```

2022-06-01 16:27 UTC, mrdrivingduck commented
This PR needs some modification before it can be merged.

2022-06-02 03:31 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +- 存在 `./tmp_basedir_polardb_pg_1100_bld/` 、 `./tmp_replica_dir_polardb_pg_1100_bld1/` 和 `./tmp_replica_dir_polardb_pg_1100_bld2/` 目录
Done

2022-06-02 03:31 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +./tmp_basedir_polardb_pg_1100_bld/bin/pg_ctl -D ./tmp_replica_dir_polardb_pg_1100_bld1/ restart
Done

2022-06-02 03:31 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +```
Done

2022-06-02 03:31 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +```
Done

2022-06-02 05:05 UTC, mrdrivingduck requested changes

2022-06-02 05:05 UTC, mrdrivingduck commented on docs/guide/tpch-on-px.md
> +更换 \<ip_address\> 和 \<port\> 为只读结点的 IP 地址和端口。
`<ip_address>` 和 `<port>`

2022-06-02 05:13 UTC, HBKO commented on docs/guide/tpch-on-px.md
> +更换 \<ip_address\> 和 \<port\> 为只读结点的 IP 地址和端口。
Done

2022-06-02 05:17 UTC, mrdrivingduck commented
Thanks for your contribution! @HBKO

2022-06-02 05:17 UTC, merged